# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    webp:
        generate: true

    resolvers:
        default:
            web_path: ~

    twig:
        mode: lazy

    filter_sets:
        cache: ~

        logo_varsports_header_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [550, 110], mode: inset }

        logo_varsports_header_png:
            format: png
            quality: 100
            filters:
                thumbnail: { size: [550, 110], mode: inset }

        logo_club_show_webp:
            format: webp
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: inset }

        logo_club_show_jpg:
            format: jpeg
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: inset }

        cover_club_show_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [1600, 400], mode: inset }

        cover_club_show_jpg:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [1600, 400], mode: inset }
        
        logo_club_list_webp:
            format: webp
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: inset }

        logo_club_list_jpg:
            format: jpeg
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: inset }

        cover_club_list_webp:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [390, 140], mode: inset }

        cover_club_list_jpg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [390, 140], mode: inset }
        
        cover_article_event_list_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [390, 140], mode: inset }

        cover_article_event_list_jpg:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [390, 140], mode: inset }

        cover_article_event_show_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [1600, 400], mode: inset }

        cover_article_event_show_jpg:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [1600, 400], mode: inset }
