twig:
    file_name_pattern: '*.twig'
    form_themes: [bootstrap_5_layout.html.twig]
    globals:
        contact_mail_varsports: '%env(CONTACT_MAIL_VARSPORTS)%'

when@test:
    twig:
        strict_variables: true
